// Sample data — replace this with database queries when you add Supabase.

export const CATEGORIES = [
  { id: "recruiting", label: "Recruiting", count: 87, color: "#FF2D87", bg: "#FFE0EE", text: "#7A0E40" },
  { id: "case-prep", label: "Case Prep", count: 64, color: "#7C3AED", bg: "#E9DDFF", text: "#3B0F7A" },
  { id: "networking", label: "Networking", count: 53, color: "#FFD800", bg: "#FFF6BD", text: "#4A3C00" },
  { id: "class", label: "Class & Group Projects", count: 49, color: "#00C2A8", bg: "#CFF7F0", text: "#003B33" },
  { id: "internship", label: "Internship Work", count: 41, color: "#FF6A1F", bg: "#FFE0CC", text: "#5C1F00" },
  { id: "modeling", label: "Excel & Modeling", count: 38, color: "#3B82F6", bg: "#DBEAFE", text: "#0F2C66" },
  { id: "decks", label: "Decks & Storytelling", count: 36, color: "#EC4899", bg: "#FCE7F3", text: "#671340" },
  { id: "personal-brand", label: "Personal Brand", count: 28, color: "#A855F7", bg: "#F0DCFF", text: "#4A148C" },
  { id: "career", label: "Career Switching", count: 22, color: "#10B981", bg: "#D1FAE5", text: "#064E3B" },
];

export const cat = (id) => CATEGORIES.find(c => c.id === id);

export const SCHOOLS = ["All schools", "Wharton", "HBS", "Stanford GSB", "Booth", "Kellogg", "Columbia", "Stern", "MIT Sloan", "Tuck", "Yale SOM", "INSEAD", "LBS"];

export const TOP_CONTRIBUTORS = [
  { rank: 1, name: "Maya Chen", handle: "maya.chen", school: "Wharton", year: "MBA1", hacks: 24, totalVotes: 8472, avgRating: 4.9, verified: true, color: "#FF2D87", streak: 12, topCategory: "case-prep" },
  { rank: 2, name: "Jacob Werner", handle: "jacobwerner", school: "Booth", year: "MBA2", hacks: 19, totalVotes: 7218, avgRating: 4.8, verified: true, color: "#7C3AED", streak: 8, topCategory: "networking" },
  { rank: 3, name: "Daniel Okafor", handle: "danielokafor", school: "Kellogg", year: "MBA1", hacks: 17, totalVotes: 6541, avgRating: 4.8, verified: true, color: "#00C2A8", streak: 15, topCategory: "recruiting" },
  { rank: 4, name: "Priya Shankar", handle: "priya_s", school: "HBS", year: "MBA1", hacks: 14, totalVotes: 5987, avgRating: 4.7, verified: true, color: "#FFD800", streak: 6, topCategory: "class" },
  { rank: 5, name: "Will Hayashi", handle: "willhayashi", school: "Stanford GSB", year: "MBA2", hacks: 13, totalVotes: 4892, avgRating: 4.9, verified: true, color: "#FF6A1F", streak: 4, topCategory: "modeling" },
  { rank: 6, name: "Alex Rivers", handle: "alexrivers", school: "Columbia", year: "MBA2", hacks: 12, totalVotes: 4204, avgRating: 4.6, verified: true, color: "#EC4899", streak: 3, topCategory: "decks" },
  { rank: 7, name: "Samira Khan", handle: "samira.khan", school: "Stern", year: "MBA2", hacks: 11, totalVotes: 3987, avgRating: 4.8, verified: true, color: "#A855F7", streak: 7, topCategory: "career" },
  { rank: 8, name: "Reese Park", handle: "reesepark", school: "Tuck", year: "MBA2", hacks: 10, totalVotes: 3421, avgRating: 4.7, verified: true, color: "#3B82F6", streak: 5, topCategory: "personal-brand" },
  { rank: 9, name: "Noah Tanaka", handle: "noah.t", school: "MIT Sloan", year: "MBA1", hacks: 9, totalVotes: 2987, avgRating: 4.5, verified: false, color: "#10B981", streak: 2, topCategory: "class" },
  { rank: 10, name: "Carlos Ramirez", handle: "carlosr", school: "Yale SOM", year: "MBA1", hacks: 8, totalVotes: 2654, avgRating: 4.7, verified: true, color: "#FF2D87", streak: 9, topCategory: "case-prep" },
];

export const RISING_STARS = [
  { rank: 1, name: "Aanya Patel", handle: "aanyap", school: "Booth", year: "MBA1", hacks: 4, weeklyVotes: 1247, color: "#FF2D87" },
  { rank: 2, name: "Marcus Lee", handle: "marcuslee", school: "Wharton", year: "MBA1", hacks: 3, weeklyVotes: 987, color: "#7C3AED" },
  { rank: 3, name: "Zara Ahmed", handle: "zaraa", school: "INSEAD", year: "MBA1", hacks: 5, weeklyVotes: 854, color: "#00C2A8" },
  { rank: 4, name: "James Park", handle: "jamesp", school: "Tuck", year: "MBA2", hacks: 2, weeklyVotes: 743, color: "#FFD800" },
  { rank: 5, name: "Nina Rossi", handle: "ninarossi", school: "LBS", year: "MBA1", hacks: 4, weeklyVotes: 612, color: "#FF6A1F" },
];

export const SCHOOL_LEADERBOARD = [
  { rank: 1, school: "Wharton", contributors: 47, hacks: 89, votes: 18472 },
  { rank: 2, school: "Booth", contributors: 38, hacks: 72, votes: 14893 },
  { rank: 3, school: "Kellogg", contributors: 31, hacks: 64, votes: 12541 },
  { rank: 4, school: "HBS", contributors: 29, hacks: 58, votes: 11987 },
  { rank: 5, school: "Stanford GSB", contributors: 24, hacks: 51, votes: 10204 },
  { rank: 6, school: "Columbia", contributors: 22, hacks: 47, votes: 8721 },
  { rank: 7, school: "Stern", contributors: 19, hacks: 38, votes: 7421 },
  { rank: 8, school: "MIT Sloan", contributors: 18, hacks: 34, votes: 6987 },
];

export const HACKS = [
  {
    id: 1,
    title: "Drill 50 case interviews in a weekend with Claude as your interviewer (and no partner needed)",
    category: "case-prep",
    author: "@maya.chen", authorName: "Maya Chen", school: "Wharton", year: "MBA1",
    source: "Reddit", sourceUrl: "https://reddit.com/r/MBA",
    votes: 1842, comments: 156, timeToSetup: "10 min",
    tools: ["Claude"],
    excerpt: "Couldn't find case partners on weekends. Built a Claude prompt that runs me through full cases — market sizing, profitability, M&A — and gives feedback like a real MBB interviewer. Got an MBB offer.",
    steps: [
      { title: "Set up the interviewer persona", body: "Tell Claude: 'You are a McKinsey EM running a case interview. Pick a random case type (profitability, market sizing, M&A, market entry, ops). Give me the prompt and wait for me to clarify before sharing data. Stay in character. Don\\'t help me — make me think.'" },
      { title: "Run the case end-to-end", body: "Treat it like the real thing. Ask clarifying questions, structure your approach out loud (literally type it), do the math by hand, synthesize. Don\\'t let yourself shortcut." },
      { title: "Ask for the feedback rubric", body: "After: 'Step out of role. Score me on the MBB rubric: structure, communication, quant, business judgment, synthesis. Where did I lose points? What would have separated me from a no hire?'" },
      { title: "Run the same case 3 days later", body: "Don\\'t move on. Re-run the exact case. Better answers prove you internalized the feedback. This is the loop most candidates skip." },
    ],
    saved: false, timeAgo: "2d",
  },
  {
    id: 2,
    title: "Send 100 cold LinkedIn messages to alumni that actually get replies (it's not personalization tokens)",
    category: "networking",
    author: "@jacobwerner", authorName: "Jacob Werner", school: "Booth", year: "MBA2",
    source: "x.com", sourceUrl: "https://x.com/jacobwerner",
    votes: 1456, comments: 203, timeToSetup: "30 min",
    tools: ["Claude", "LinkedIn Sales Nav"],
    excerpt: "Reply rate went from 8% to 47%. The trick wasn't 'Hi {firstName}' — it was finding the one specific thing in their background that overlapped with my pitch. Claude does that scan in seconds.",
    steps: [
      { title: "Build your target list", body: "Use LinkedIn alumni search. Filter by your school + target firm + 2-7 years out (close enough to remember, senior enough to refer). Export 100 names with their profile URLs." },
      { title: "Scrape one profile per message", body: "For each person, paste their About + Experience into Claude with: 'Find ONE specific thing in this person\\'s background — a project, a role transition, a public talk — that I can reference. Not their school, not their title. Something they\\'d be slightly surprised I noticed.'" },
      { title: "Generate the message", body: "Then: 'Write a 4-sentence LinkedIn message from a [your school] [year] interested in [their function]. Reference [the specific thing]. End with a 15-min ask, not a 30-min one. No flattery.'" },
      { title: "Track and iterate weekly", body: "Spreadsheet: name, firm, sent date, reply (Y/N), what worked. After 25, you\\'ll see patterns. Double down on the openers that are converting." },
    ],
    saved: true, timeAgo: "5d",
  },
  {
    id: 3,
    title: "Turn the 60-page case reading into a 10-minute prep that actually impresses the cold caller",
    category: "class",
    author: "@priya_s", authorName: "Priya Shankar", school: "HBS", year: "MBA1",
    source: "Reddit", sourceUrl: "https://reddit.com/r/MBA",
    votes: 1287, comments: 94, timeToSetup: "5 min",
    tools: ["Claude"],
    excerpt: "Stopped reading cases linearly. Now I have Claude pull the protagonist's dilemma, the financials that matter, and the 3 questions a prof would actually cold call on. Got cold-called twice last week — nailed both.",
    steps: [
      { title: "Upload the case PDF", body: "Drop it into Claude. The full case — exhibits and all. Don\\'t summarize first." },
      { title: "Ask for the protagonist map", body: "'Who is the protagonist, what decision are they facing, what are the 2-3 options, and what\\'s the deadline? In 100 words total.'" },
      { title: "Get the cold-call list", body: "'Generate 5 questions a tough HBS-style professor would cold call on. For each, give me a defensible 30-second answer using specific exhibits. Cite which exhibit.'" },
      { title: "Find the contrarian take", body: "'What\\'s the consensus take in class likely to be? Now give me a defensible contrarian view — one a sharp student could defend with the data.' This is what gets you remembered." },
    ],
    saved: false, timeAgo: "1d",
  },
  {
    id: 4,
    title: "Build a 'recruiting OS' in Notion + Claude that runs your entire summer internship search",
    category: "recruiting",
    author: "@danielokafor", authorName: "Daniel Okafor", school: "Kellogg", year: "MBA1",
    source: "x.com", sourceUrl: "https://x.com/danielokafor",
    votes: 1102, comments: 78, timeToSetup: "45 min",
    tools: ["Notion", "Claude"],
    excerpt: "Tracked 47 firms, 89 contacts, 23 coffee chats, 11 first-rounds in one Notion database. Claude prepped me for every single touchpoint using the data I'd already logged. Got 4 offers.",
    steps: [
      { title: "Build the Notion schema", body: "Three tables: Firms (name, vertical, status, deadline, why-fit), Contacts (name, firm, role, last contact, notes), Touchpoints (date, person, channel, what we discussed, follow-up). Link them." },
      { title: "Log every single conversation", body: "5 minutes after every coffee chat or call: dump notes into the Touchpoints table. Names dropped, what they cared about, anything personal." },
      { title: "Pre-meeting prep prompt", body: "Before a chat: paste the contact\\'s history + LinkedIn into Claude: 'Based on our last 3 touchpoints, what should I open with? What questions haven\\'t I asked? What signal am I trying to send in this conversation?'" },
      { title: "Weekly pipeline review with Claude", body: "Every Sunday: paste your full pipeline status. Ask: 'Which firms am I drifting on? Who haven\\'t I followed up with in 14+ days? Which conversations need a specific next step?'" },
    ],
    saved: false, timeAgo: "1w",
  },
  {
    id: 5,
    title: "Build the Excel model in 20 min instead of 4 hours by having Claude write the formulas (not the numbers)",
    category: "modeling",
    author: "@willhayashi", authorName: "Will Hayashi", school: "Stanford GSB", year: "MBA2",
    source: "x.com", sourceUrl: "https://x.com/willhayashi",
    votes: 967, comments: 112, timeToSetup: "20 min",
    tools: ["Claude", "Excel"],
    excerpt: "The mistake people make is asking Claude to 'build a model.' Don't. Have it write the formulas, sheet structure, and assumption logic — then you build it. You learn it AND it's faster.",
    steps: [
      { title: "Describe the model in plain English", body: "Tell Claude: 'I need a 5-year DCF for a SaaS company with [unit economics]. Give me: (1) the sheet structure, (2) the assumption tab inputs, (3) the formulas for revenue build, COGS, OpEx, FCF, and terminal value. Don\\'t fill in numbers — just the architecture.'" },
      { title: "Build the sheets manually", body: "Set up the tabs Claude described. Type the formulas yourself — don\\'t paste. The act of typing them is what makes you understand the model when someone asks." },
      { title: "Sanity-check with assumption sweeps", body: "Once built: 'Here are my assumptions [paste]. Are any of these unreasonable for this industry? Show me a bull/base/bear case range for the 3 most sensitive inputs.'" },
      { title: "Stress test before you ship", body: "Before sending to your boss: 'What\\'s the question my MD is most likely to ask about this model? What weak point would they probe?' Fix it before they find it." },
    ],
    saved: false, timeAgo: "3d",
  },
  {
    id: 6,
    title: "Make a McKinsey-quality consulting deck in 90 min using the 'pyramid principle' prompt",
    category: "decks",
    author: "@alexrivers", authorName: "Alex Rivers", school: "Columbia", year: "MBA2",
    source: "Reddit", sourceUrl: "https://reddit.com/r/MBA",
    votes: 854, comments: 67, timeToSetup: "90 min",
    tools: ["Claude", "PowerPoint"],
    excerpt: "Group project deck went from 'student-tier' to 'partner asked who built it.' The unlock was forcing the storyline before any slides got designed.",
    steps: [
      { title: "Lock the governing thought first", body: "Tell Claude: 'I need to make a recommendation on [topic]. My thesis is [X]. Using the Minto pyramid, give me the governing thought + 3 supporting arguments + 2-3 sub-points each. Be ruthless about MECE.'" },
      { title: "Generate slide titles as full sentences", body: "'Now write each slide title as a complete sentence that makes the argument. The deck should be readable as just titles — like a McKinsey deck.'" },
      { title: "Get the so what for each slide", body: "For every slide: 'What\\'s the one chart or piece of evidence that proves this title? Describe it in one sentence so I know what to build.'" },
      { title: "Pre-mortem the recommendation", body: "Before you finalize: 'You\\'re a skeptical SVP. What are the 3 biggest holes in this argument? What would you ask the team that they probably haven\\'t prepared for?' Add a backup slide for each." },
    ],
    saved: true, timeAgo: "4d",
  },
  {
    id: 7,
    title: "Crack any 'tell me about yourself' for a career switcher with this 4-part script",
    category: "career",
    author: "@samira.khan", authorName: "Samira Khan", school: "Stern", year: "MBA2",
    source: "x.com", sourceUrl: "https://x.com/samirakhan",
    votes: 743, comments: 89, timeToSetup: "30 min",
    tools: ["Claude"],
    excerpt: "Switching from teaching to product. Every interview asked 'why this pivot' and I fumbled it. Claude helped me build a 90-second answer that turned my background into the asset, not the apology.",
    steps: [
      { title: "Tell Claude your full story", body: "Not the resume version — the real one. 'I was a [prior role]. I left because [real reason]. I want [target role] because [real motivation].' Give it 5+ paragraphs. The depth is what makes the output good." },
      { title: "Ask for the 4-part frame", body: "'Build a 90-second tell me about yourself for a [target role] interview. Use this structure: (1) the through-line my career has had all along, (2) why MBA now, (3) what I\\'m chasing in [target role], (4) why this firm specifically. Make my prior experience an asset.'" },
      { title: "Stress test against the real objection", body: "'A skeptical interviewer hears my pitch and thinks: Why should I bet on someone with no [function] experience? Write the 30-second answer to that.'" },
      { title: "Drill the delivery", body: "Record yourself saying it 5 times. Send the transcript back: 'Where am I hedging? Where am I apologizing? Cut the wishy-washy language.'" },
    ],
    saved: false, timeAgo: "6d",
  },
  {
    id: 8,
    title: "Turn your dead group project chat into a working timeline in 5 minutes",
    category: "class",
    author: "@noah.t", authorName: "Noah Tanaka", school: "MIT Sloan", year: "MBA1",
    source: "Reddit", sourceUrl: "https://reddit.com/r/MBA",
    votes: 612, comments: 41, timeToSetup: "5 min",
    tools: ["Claude"],
    excerpt: "Group projects turn into 200-message Slack chaos. Export the channel, paste into Claude, get a clean 'who said they'd do what by when.' Saved my team 3 hours of arguing over what was decided.",
    steps: [
      { title: "Export the channel", body: "In Slack: channel settings → export. In WhatsApp: chat → export → without media. Paste the .txt into Claude." },
      { title: "Pull commitments", body: "Prompt: 'This is my group project chat. Extract every commitment anyone made — who said they\\'d do what, by when. Note any commitments that contradict each other. Flag commitments without owners.'" },
      { title: "Surface unresolved decisions", body: "'Now list every decision we discussed but never closed on. For each one, give me the 2-3 options that were on the table.'" },
      { title: "Generate the recap message", body: "'Write a Slack message I can post tonight that says: here\\'s what we committed to, here\\'s what\\'s still open, here\\'s what each person owes by Sunday. Keep it under 200 words.'" },
    ],
    saved: false, timeAgo: "12h",
  },
  {
    id: 9,
    title: "Generate a personal brand on LinkedIn that recruiters actually find (not the 'thrilled to announce' kind)",
    category: "personal-brand",
    author: "@reesepark", authorName: "Reese Park", school: "Tuck", year: "MBA2",
    source: "x.com", sourceUrl: "https://x.com/reesepark",
    votes: 534, comments: 72, timeToSetup: "60 min",
    tools: ["Claude", "LinkedIn"],
    excerpt: "Got recruited for my dream PE role through inbound. The trick: Claude analyzed 50 posts from people who got jobs in my target space, found the patterns, and helped me write in that lane.",
    steps: [
      { title: "Build the comparable corpus", body: "Find 10-15 people 2-5 years ahead of you in your target role. Copy their last 20 LinkedIn posts each. Paste into Claude as one document." },
      { title: "Extract the patterns", body: "'These are 200 posts from people who landed [target role]. What patterns do you see in: topics they cover, post structures they use, the specificity of their points, what they reveal about themselves?'" },
      { title: "Pick your three lanes", body: "'Based on my background [paste], pick 3 content lanes I could credibly own that overlap with what gets engagement in this space. Each lane should give me 20+ post ideas.'" },
      { title: "Draft the first 10 posts", body: "'Write 10 posts in my voice in those 3 lanes. Each should make ONE specific point with a concrete example. No thrilled to announce. No platitudes. Sound like a sharp peer, not a thought leader.'" },
    ],
    saved: false, timeAgo: "2w",
  },
];
